### ISSUE TITLE
How to override aws region?

### ISSUE THREAD

**Issue by dale-c-anderson** [tomaszkiewicz/prometheus-alertmanager-cloudwatch-webhook#4]
I see in the [go file that the region *can* be overridden](https://github.com/tomaszkiewicz/prometheus-alertmanager-cloudwatch-webhook/blob/master/cmd/webhook/main.go), but stumped as to actually do it. Got any tips @tomaszkiewicz ?  My alerts should be going to Canada, but they're ending up in Ireland. :rofl:

**Comment by tomaszkiewicz** [comment]
Just set REGION env variable to a desired region and it should work :)

**Comment by dale-c-anderson** [comment]
Thanks @tomaszkiewicz  - i tried `region` at first, but didn't realize that it had to be uppercase. It's working now. :+1:
