### ISSUE TITLE
IMDSv2 update

### ISSUE THREAD

**Issue by oussemabhouri** [tomaszkiewicz/prometheus-alertmanager-cloudwatch-webhook#5]
Does it work with AWS IMDSv2 ? If not, shouldn't you do the needed changes for that?

**Comment by tomaszkiewicz** [comment]
It depends on way you use to get the credentials. If you use kube2iam (as in my examples) it all depends on a version of kube2iam.
Also, the application itself doesn't expose anything that can be used to hijack credentials using v1.

**Comment by oussemabhouri** [comment]
updating aws-sdk-go fixed it
